from tkinter import *
from tkinter import ttk
import csv
import pandas as pd
def Credit():
    with open("E:\\Python projects\\First GUI\\balance.csv",'a+',newline='') as bal:
        a=csv.writer(bal,delimiter=',')
        data=[[Input_name.get(),Input_date.get(),Input_amount.get(),Input_description.get()]]
        a.writerows(data)
    Input_name.delete(0,END)
    Input_date.delete(0,END)
    Input_amount.delete(0,END)
    Input_description.delete(0,END)
    bals=pd.read_csv("E:\\Python projects\\First GUI\\balance.csv")
    bals.fillna(0,inplace=True)
    creditSum=sum(bals['creditAmount'])
    debitSum=sum(bals['debitAmount'])
    res=abs(creditSum-debitSum)
    Label(balance_labelframe,text=res,font=("arial 10 bold")).place(x=127,y=172)
    bals['creditDate']=pd.to_datetime(bals['creditDate'],yearfirst=False)
    bals['debitDate']=pd.to_datetime(bals['debitDate'],yearfirst=False)
def Debit():
    with open("E:\\Python projects\\First GUI\\balance.csv",'a+',newline='') as bal:
        a=csv.writer(bal,delimiter=',')
        data=[["","","","",Input_name.get(),Input_date.get(),Input_amount.get(),Input_description.get()]]
        a.writerows(data)
    Input_name.delete(0,END)
    Input_date.delete(0,END)
    Input_amount.delete(0,END)
    Input_description.delete(0,END)
    bals=pd.read_csv("E:\\Python projects\\First GUI\\balance.csv")
    bals.fillna(0,inplace=True)
    creditSum=sum(bals['creditAmount'])
    debitSum=sum(bals['debitAmount'])
    res=abs(creditSum-debitSum)
    Label(balance_labelframe,text=res,font=("arial 10 bold")).place(x=127,y=172)
    bals['creditDate']=pd.to_datetime(bals['creditDate'],yearfirst=False)
    bals['debitDate']=pd.to_datetime(bals['debitDate'],yearfirst=False)
def finalBalance():
    bals=pd.read_csv("E:\\Python projects\\First GUI\\balance.csv")
    bals.fillna(0,inplace=True)
    creditSum=sum(bals['creditAmount'])
    debitSum=sum(bals['debitAmount'])
    res=abs(creditSum-debitSum)
    Label(balance_labelframe,text=res,font=("arial 10 bold")).place(x=127,y=172)
def displayAll():
    print("Display all")
def viewBorrower():
    print("View borrower")
def complete():
    print("Complete")
def create():
    print("Created")
root=Tk()
# root.geometry("500x355")
root.title("Record")
var=ttk.Notebook(root)
var.grid()
balance_frame=ttk.Frame(var)
borrower_frame=ttk.Frame(var)
var.add(balance_frame,text="Balance")
var.add(borrower_frame,text="Borrower")
balance_labelframe=ttk.LabelFrame(balance_frame,height="355",width="500",text='Balance')
# input_name=StringVar()
# input_amount=IntVar()
# input_date=StringVar()
# input_description=StringVar()
label_name=Label(balance_labelframe,text="Name:")
label_amount=Label(balance_labelframe,text="Amount:")
label_date=Label(balance_labelframe,text="Date:")
label_description=Label(balance_labelframe,text="Description:")
Input_name=ttk.Entry(balance_labelframe,width=20)
Input_amount=ttk.Entry(balance_labelframe,width=20)
Input_date=ttk.Entry(balance_labelframe,width=20)
Input_description=ttk.Entry(balance_labelframe,width=20)
label_name.grid(row=0,column=2)
Input_name.grid(row=0,column=3)
label_amount.grid(row=1,column=2)
Input_amount.grid(row=1,column=3)
label_date.grid(row=2,column=2)
Input_date.grid(row=2,column=3)
label_description.grid(row=3,column=2)
Input_description.grid(row=3,column=3)
credit_button=ttk.Button(balance_labelframe,text="Credit",command=Credit).place(x=10,y=100)
debit_button=ttk.Button(balance_labelframe,text="Debit",command=Debit).place(x=100,y=100)
Label(balance_labelframe,text="Final Balance:",font=("arial 12 bold")).place(x=10,y=170)
options_balance=ttk.LabelFrame(balance_labelframe,height="160",width="120",text="Options")
view_all=ttk.Button(options_balance,text="View all",command=displayAll).place(x=20,y=20)
final_bal=ttk.Button(options_balance,text="Final balance",command=finalBalance).place(x=20,y=80)
options_balance.grid(row=6,column=4)
balance_labelframe.grid(row=0,column=0)
borrower_labelframe=ttk.LabelFrame(borrower_frame,height="355",width="310",text='Borrower')
# inputb_name=StringVar()
# inputb_amount=IntVar()
# inputb_date=StringVar()
# inputb_duration=StringVar()
# inputb_finalAmount=IntVar()
labelb_name=ttk.Label(borrower_labelframe,text="Name :").grid(row=0,column=2)
Inputb_name=ttk.Entry(borrower_labelframe,width=20).grid(row=0,column=3)
labelb_amount=ttk.Label(borrower_labelframe,text="Amount :").grid(row=1,column=2)
Inputb_amount=ttk.Entry(borrower_labelframe,width=20).grid(row=1,column=3)
labelb_date=ttk.Label(borrower_labelframe,text="Date :").grid(row=2,column=2)
Inputb_date=ttk.Entry(borrower_labelframe,width=20).grid(row=2,column=3)
labelb_duration=ttk.Label(borrower_labelframe,text="Duration :").grid(row=3,column=2)
Inputb_duration=ttk.Entry(borrower_labelframe,width=20).grid(row=3,column=3)
labelb_finalamount=ttk.Label(borrower_labelframe,text="Final Amount :").grid(row=4,column=2)
Inputb_finalamount=ttk.Entry(borrower_labelframe,width=20).grid(row=4,column=3)
options_borrower=ttk.LabelFrame(borrower_labelframe,height="160",width="120",text="Options")
view_all=ttk.Button(options_borrower,text="View all",command=displayAll).place(x=24,y=15)
detail=ttk.Button(options_borrower,text="View Borrower",command=viewBorrower).place(x=22,y=55)
complete=ttk.Button(options_borrower,text="Complete Case",command=complete).place(x=20,y=95)
create=ttk.Button(borrower_labelframe,text="Create",command=create).place(x=50,y=120)
options_borrower.grid(row=6,column=4)
borrower_labelframe.grid()
root.mainloop()